_format_version: "1.1"
services:
- url: http://example.com
  routes:
  - paths:
    - "/"
  plugins:
  - name: go-keycloak
    config:
      mode: Enforce
      client_id: test-client
      secret: ba15024a-725b-45ea-bac2-c70332e4c4d7
      server_uri: http://keycloak:8080/auth
      realm: test
      rules:
        - testResource:testScope